---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kubernetes-image-reader
  namespace: crowdstrike-slack
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: lodgify-factory-gcp-secretsmanager
  target:
    name: kubernetes-image-reader
    template:
      type: kubernetes.io/dockerconfigjson
    creationPolicy: Owner
  data:
  - secretKey: .dockerconfigjson
    remoteRef:
      key: k8s_infra_image_pull_secrets
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cs-slack-client-id
  namespace: crowdstrike-slack
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: lodgify-factory-gcp-secretsmanager
  target:
    name: cs-slack-client-id         # Reference this in your resources.yaml - .env[0].valueFrom.secretKeyRef.name
    creationPolicy: Owner
  data:
  - secretKey: client-id             # Reference this in your deployment - .env[0].valueFrom.secretKeyRef.key
    remoteRef:
      key: k8s_secops_crowdstrikeslack_client_id # <- This is the name of the secret in GCP Secret Manager
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cs-slack-client-secret
  namespace: cloudflare-slack
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: lodgify-factory-gcp-secretsmanager
  target:
    name: cs-slack-client-secret       # Reference this in your resources.yaml - .env[0].valueFrom.secretKeyRef.name
    creationPolicy: Owner
  data:
  - secretKey: client-secret           # Reference this in your deployment - .env[0].valueFrom.secretKeyRef.key
    remoteRef:
      key: k8s_secops_crowdstrikeslack_client_secret  # <- This is the name of the secret in GCP Secret Manager
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cs-slack-slack-token
  namespace: crowdstrike-slack
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: lodgify-factory-gcp-secretsmanager
  target:
    name: cs-slack-slack-token         # Reference this in your resources.yaml - .env[0].valueFrom.secretKeyRef.name
    creationPolicy: Owner
  data:
  - secretKey: slack-token             # Reference this in your deployment - .env[0].valueFrom.secretKeyRef.key
    remoteRef:
      key: k8s_secops_crowdstrikeslack_slack_token # <- This is the name of the secret in GCP Secret Manager